# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSFAqwYkbQ_jonAPO8YuWthehx_q4MZb
"""

# src/skin_match/cleaning.py

import pandas as pd

def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean raw skincare dataframe:
    - remove duplicates
    - fix data types
    - standardize text fields
    """

    df = df.copy()

    # remove duplicates
    df = df.drop_duplicates()

    # numeric fields
    if "price" in df.columns:
        df["price"] = pd.to_numeric(df["price"], errors="coerce")

    if "rank" in df.columns:
        df["rank"] = pd.to_numeric(df["rank"], errors="coerce")

    # text normalization
    if "ingredients" in df.columns:
        df["ingredients"] = (
            df["ingredients"]
            .astype(str)
            .str.lower()
            .str.strip()
        )

    return df