# -*- coding: utf-8 -*-
"""recommend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkdUKvMcTyIs5Z5el7LAAg9Fkwzhqcm_
"""

# src/skinmatch/recommend.py
import pandas as pd

SKIN_TYPES = ["Combination", "Dry", "Normal", "Oily", "Sensitive"]

def recommend_top_products(df_mart: pd.DataFrame,
                           skin_type: str,
                           target_effects=None,
                           max_price: float = None,
                           max_risk: float = None,
                           top_n: int = 10,
                           verbose: bool = True) -> pd.DataFrame:
    """
    Rule-based SkinMatch recommender.

    Parameters
    ----------
    skin_type : str
        One of ["Combination", "Dry", "Normal", "Oily", "Sensitive"].
    target_effects : list or None
        List of desired primary_effect values, e.g. ["hydrating", "soothing_barrier"].
        If None, do not filter on primary_effect.
    max_price : float or None
        Maximum acceptable price; if None, do not filter on price.
    max_risk : float or None
        Maximum acceptable risk_score; if None, do not filter on risk.
    top_n : int
        Number of products to return.
    verbose : bool
        If True, print a short summary of the filters.
    """
    # 1. basic input cleaning
    valid_skin_types = ["Combination", "Dry", "Normal", "Oily", "Sensitive"]
    if skin_type not in valid_skin_types:
        raise ValueError(f"skin_type must be one of {valid_skin_types}")

    # start from mart
    rec_df = df_mart.copy()

    # 2. filter by skin type flag = 1
    rec_df = rec_df[rec_df[skin_type] == 1]

    # 3. filter by desired effects
    if target_effects is not None and len(target_effects) > 0:
        rec_df = rec_df[rec_df["primary_effect"].isin(target_effects)]

    # 4. filter by price
    if max_price is not None:
        rec_df = rec_df[rec_df["price"] <= max_price]

    # 5. filter by risk_score
    if max_risk is not None:
        rec_df = rec_df[rec_df["risk_score"] <= max_risk]

    # 6. sort products: first by rank (higher better), then by lower risk, then by price
    rec_df = rec_df.sort_values(
        by=["rank", "risk_score", "price"],
        ascending=[False, True, True]
    )

    # 7. choose columns to display
    display_cols = [
        "brand", "Label", "name", "price", "rank",
        "primary_effect", "risk_score",
        "Combination", "Dry", "Normal", "Oily", "Sensitive"
    ]
    rec_df = rec_df[display_cols].head(top_n)

    if verbose:
        print("=== SkinMatch Recommendation ===")
        print(f"Skin type: {skin_type}")
        if target_effects:
            print(f"Target effects: {', '.join(target_effects)}")
        if max_price is not None:
            print(f"Max price: {max_price}")
        if max_risk is not None:
            print(f"Max risk score: {max_risk}")
        print(f"Returned top {len(rec_df)} products.\n")

    return rec_df