# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AgI3cUIyomB6LTZhySNUwWqcdEN8lru
"""

# src/skinmatch/data.py
import pandas as pd

RAW_URL = "https://raw.githubusercontent.com/rainyliurunlin/SkinMatch/refs/heads/main/skincare_ingredients.csv"

def load_raw_data(url: str = RAW_URL) -> pd.DataFrame:
    try:
        df = pd.read_csv(url)
    except UnicodeDecodeError:
        df = pd.read_csv(url, encoding="latin-1")
    return df

def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    df_clean = df.copy()
    df_clean = df_clean[~df_clean["ingredients"].isna()]
    df_clean["price"] = pd.to_numeric(df_clean["price"], errors="coerce")
    df_clean = df_clean[~df_clean["price"].isna()]
    df_clean = df_clean.drop_duplicates(subset=["brand", "name"])
    df_clean.columns = [c.strip() for c in df_clean.columns]
    return df_clean