# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySCZSnerNs9z2CK2dqpBZcNDx2e9Am1I
"""

# src/skinmatch/features.py
import pandas as pd

EFFECT_KEYWORDS = {
    "hydrating": [
        "hyaluronic acid", "sodium hyaluronate", "glycerin",
        "squalane", "panthenol", "butylene glycol"
    ],
    "brightening": [
        "niacinamide", "ascorbic acid", "vitamin c", "alpha arbutin",
        "licorice", "kojic acid"
    ],
    "anti_acne": [
        "salicylic acid", "bha", "benzoyl peroxide", "sulfur", "tea tree"
    ],
    "anti_aging": [
        "retinol", "retinal", "peptide", "peptides",
        "collagen", "ferulic acid"
    ],
    "soothing_barrier": [
        "ceramide", "ceramides", "centella", "madecassoside",
        "panthenol", "allantoin"
    ]
}

RISK_KEYWORDS = {
    # kw : score
    "fragrance": 2,
    "parfum": 2,
    "perfume": 2,
    "alcohol denat": 2,
    "denatured alcohol": 2,
    "limonene": 1,
    "linalool": 1,
    "citral": 1,
    "eugenol": 1,
    "geraniol": 1,
    "citronellol": 1,
    "aha": 1,
    "glycolic acid": 1,
    "lactic acid": 1
}

def normalize_ingredients(text: str) -> str:
    """
    Standardize the raw ingredients string:
      - Convert to lowercase
      - Replace line breaks with spaces
      - Remove the extra spaces
    """
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = text.replace("\n", " ")
    text = " ".join(text.split())
    return text

def count_ingredients(text: str) -> int:
    """
    Estimate the number of ingredients through commas.
    """
    if not text:
        return 0
    return len([x for x in text.split(",") if x.strip()])

def detect_effect(ingredients_text: str) -> str:
    """
    Judge the main efficacy of the product based on the key words.
    If multiple functions are hit, take the first one according to the following priority.
    If none of them exists, it will be marked as 'other'.
    """
    if not ingredients_text:
        return "other"

    effects_found = []
    for effect, keywords in EFFECT_KEYWORDS.items():
        for kw in keywords:
            if kw in ingredients_text:
                effects_found.append(effect)
                break

    if not effects_found:
        return "other"

    priority = ["soothing_barrier", "hydrating", "anti_acne", "brightening", "anti_aging"]
    for p in priority:
        if p in effects_found:
            return p

    return effects_found[0]

def calc_risk_score(ingredients_text: str) -> int:
    """
    Simple risk scoring model:
      For each high-risk/potential sensitizing ingredient hit, the corresponding score will be added.
    """
    if not ingredients_text:
        return 0

    score = 0
    for kw, kw_score in RISK_KEYWORDS.items():
        if kw in ingredients_text:
            score += kw_score
    return score

def add_basic_features(df_clean: pd.DataFrame) -> pd.DataFrame:
    df = df_clean.copy()
    df["ingredients_clean"] = df["ingredients"].apply(normalize_ingredients)
    df["ingredient_count"] = df["ingredients_clean"].apply(count_ingredients)
    df["primary_effect"] = df["ingredients_clean"].apply(detect_effect)
    df["risk_score"] = df["ingredients_clean"].apply(calc_risk_score)
    return df