# -*- coding: utf-8 -*-
"""mart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEqBs4RKOL2eytTU3F6JLZymtsjhtXto
"""

# src/skinmatch/mart.py
import pandas as pd

SKIN_TYPES = ["Combination", "Dry", "Normal", "Oily", "Sensitive"]

def build_mart(df: pd.DataFrame) -> pd.DataFrame:
    mart_cols = [
        "brand", "Label", "name", "price", "rank",
        "ingredient_count", "primary_effect", "risk_score",
        *SKIN_TYPES
    ]
    return df[mart_cols].copy()