# -*- coding: utf-8 -*-
"""skinmatch_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14L09Nqm9KGdlWbgCrP_RYpQAwdj7nuMl
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/rainyliurunlin/SkinMatch.git
# %cd SkinMatch
!ls

import sys
sys.path.append("/content/SkinMatch/src")

import skin_match
print("Imported skin_match successfully.")

import pandas as pd

df = pd.read_csv("data/skincare_ingredients.csv")
df.shape, df.columns

"""# SkinMatch: Ingredient-Based Skincare Analytics & Recommendation System

**Author:** Runlin Liu  

SkinMatch is a data-driven skincare analytics project designed to explore how cosmetic ingredients, product categories, and skin-type suitability relate to pricing, user ratings, and product effectiveness.

Using a real-world skincare ingredients dataset, this project aims to:

- Analyze ingredient composition and product characteristics across skincare categories
- Engineer interpretable features such as ingredient count, primary skincare effect, and irritation risk
- Identify pricing and rating patterns through exploratory data analysis
- Demonstrate a rule-based recommendation system tailored to different skin types and skincare goals

This notebook serves as an end-to-end demonstration of the SkinMatch analytics pipeline, while the core logic is implemented as reusable Python modules under `src/skin_match`.

## Data Source and Problem Statement

The dataset used in this project is a publicly available skincare product dataset containing information on:

- Product category and brand
- Price and user rating
- Full ingredient lists
- Binary indicators for skin-type suitability (Combination, Dry, Normal, Oily, Sensitive)

**Problem motivation:**

Skincare consumers often struggle to evaluate products beyond marketing claims. Ingredient lists are complex, and relationships between ingredients, skin types, price, and perceived effectiveness are not always obvious.

This project explores the following questions:

1. How do price and user ratings vary across product categories and primary skincare effects?
2. Can ingredient-level features help characterize products in a meaningful and interpretable way?
3. How can simple rules based on ingredients and skin type be used to generate personalized product recommendations?
"""

import pandas as pd

df = pd.read_csv("data/skincare_ingredients.csv")

print(f"Dataset shape: {df.shape}")
df.head()

"""## Initial Data Inspection

Before cleaning and feature engineering, we perform a quick inspection of the raw dataset to understand its structure, data types, and potential issues.

"""

df.info()

# --- Setup: clone repo & import local package ---
import sys, os

REPO_DIR = "/content/SkinMatch"
SRC_DIR = os.path.join(REPO_DIR, "src")

if SRC_DIR not in sys.path:
    sys.path.append(SRC_DIR)

import skin_match
print("Imported skin_match successfully.")

import pandas as pd

DATA_PATH = os.path.join(REPO_DIR, "data", "skincare_ingredients.csv")
df_raw = pd.read_csv(DATA_PATH)

print("Raw shape:", df_raw.shape)
display(df_raw.head(3))
df_raw.info()

import pandas as pd

def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # standardize column names (optional)
    df.columns = [c.strip() for c in df.columns]

    # drop duplicates
    df = df.drop_duplicates()

    # strip text columns
    for col in ["Label", "brand", "name", "ingredients"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

    # enforce numeric types
    if "price" in df.columns:
        df["price"] = pd.to_numeric(df["price"], errors="coerce")
    if "rank" in df.columns:
        df["rank"] = pd.to_numeric(df["rank"], errors="coerce")

    # drop rows missing key fields
    df = df.dropna(subset=["Label", "brand", "name", "price", "rank", "ingredients"])

    return df

"""## Data Cleaning

The cleaning pipeline standardizes text fields, removes duplicates,
ensures consistent data types, and filters incomplete records.

After cleaning, the dataset remains at 1,472 products with no missing values,
preserving the original dataset size while improving analytical reliability.
"""

from skin_match import clean_dataframe

df = clean_dataframe(df_raw)

print("Cleaned shape:", df.shape)
display(df.head(3))
df.isna().sum()

print("Before:", df_raw.shape)
print("After :", df.shape)

df.describe(include="all").T.head(12)

"""## Feature Engineering

To enable deeper analysis, I derived several interpretable features, including:

- Ingredient count per product
- Primary skincare effect classification
- Risk-related indicators based on ingredient patterns

These engineered features allow analysis beyond raw product metadata.
"""

from skin_match.features import add_basic_features

df_feat = add_basic_features(df)
df_feat.head()

"""## Analytical Data Mart

A focused data mart was created by isolating variables relevant to pricing,
ratings, skincare effects, and skin-type suitability.

This structure simplifies downstream analysis and improves reproducibility.

"""

from skin_match.mart import build_mart

df_mart = build_mart(df_feat)
df_mart.head()

"""## Exploratory Analysis

### 1. Price Distribution by Primary Effect

"""

import seaborn as sns
import matplotlib.pyplot as plt
sns.boxplot(data=df_mart, x="primary_effect", y="price")
plt.title("Price Distribution by Primary Effect")
plt.xticks(rotation=45)
plt.show()

"""### 2. Rating Distribution Across Product Categories

"""

sns.boxplot(data=df_mart, x="Label", y="rank")
plt.xticks(rotation=45)
plt.title("Product Rating Distribution Across Product Categories")
plt.show()

"""## Recommendation Prototype

Based on engineered features and skin-type labels, a simple rule-based
recommendation function selects top-rated products suitable for a given skin type.

This prototype demonstrates how analytical insights can be translated
into user-facing decision support.

"""

from skin_match.recommend import recommend_top_products

recommend_top_products(
    df_mart,
    skin_type="Oily",
    top_n=5
)

"""## Conclusion & Future Work

This project demonstrates how structured data cleaning, feature engineering,
and exploratory analysis can support transparent skincare recommendations.

Future extensions may include:
- Ingredient embedding and similarity-based recommendation
- Sentiment analysis using product reviews
- A lightweight web interface for interactive exploration

"""